###################
# FOR PRODUCTION #
###################

version: "3.7"

services:
  # Database
  db:
    # Using custom mysql image
    image: image
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: website
    ports:
      - "3308:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  # Main website
  nextjs:
    image: image
    container_name: personalwebsite
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    restart: always

  # Reverse proxy
  nginx:
    image: image
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    links:
      - nextjs
    restart: always
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  # Automatic renewal of SSL
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    links:
      - nginx
    restart: always

    # Cronjob for fetching data from external APIs
  cronjob:
    image: image
    container_name: cronjob
    links:
      - nextjs
      - db
    restart: always
    depends_on:
      - db
